package com.inspur.playwork.utils.db.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.UnsupportedEncodingException;

import javax.mail.internet.InternetAddress;

/**
 * Entity mapped to table "MAIL_CONTACTS".
 */
public class MailContacts extends InternetAddress{

    private Long id;
    /** Not-null value. */

    public MailContacts() {
    }

    public MailContacts(Long id) {
        this.id = id;
    }

    public MailContacts(String address, String personal) throws UnsupportedEncodingException {
        this.setAddress(address);
        this.setPersonal(personal);
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
}
