package com.inspur.playwork.utils.db.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MAIL_ACCOUNT".
 */
public class MailAccount {

    private Long id;
    /** Not-null value. */
    private String userId;
    private String displayName;
    private String nickName;
    /** Not-null value. */
    private String email;
    private String account;
    private String password;
    private String inComingHost;
    private String inComingPort;
    private boolean inComingSSL;
    private String outGoingHost;
    private String outGoingPort;
    private boolean outGoingSSL;
    private boolean outGoingTLS;
    private String protocol;
    private boolean defaultEncryptMail;
    private boolean defaultSignMail;
    private boolean enabled;

    public MailAccount() {
    }

    public MailAccount(Long id) {
        this.id = id;
    }

    public MailAccount(Long id, String userId, String displayName, String nickName, String email, String account, String password, String inComingHost, String inComingPort, boolean inComingSSL, String outGoingHost, String outGoingPort, boolean outGoingSSL, boolean outGoingTLS, String protocol, boolean defaultEncryptMail, boolean defaultSignMail, boolean enabled) {
        this.id = id;
        this.userId = userId;
        this.displayName = displayName;
        this.nickName = nickName;
        this.email = email;
        this.account = account;
        this.password = password;
        this.inComingHost = inComingHost;
        this.inComingPort = inComingPort;
        this.inComingSSL = inComingSSL;
        this.outGoingHost = outGoingHost;
        this.outGoingPort = outGoingPort;
        this.outGoingSSL = outGoingSSL;
        this.outGoingTLS = outGoingTLS;
        this.protocol = protocol;
        this.defaultEncryptMail = defaultEncryptMail;
        this.defaultSignMail = defaultSignMail;
        this.enabled = enabled;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUserId() {
        return userId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getNickName() {
        return nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /** Not-null value. */
    public String getEmail() {
        return email;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEmail(String email) {
        this.email = email;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getInComingHost() {
        return inComingHost;
    }

    public void setInComingHost(String inComingHost) {
        this.inComingHost = inComingHost;
    }

    public String getInComingPort() {
        return inComingPort;
    }

    public void setInComingPort(String inComingPort) {
        this.inComingPort = inComingPort;
    }

    public boolean getInComingSSL() {
        return inComingSSL;
    }

    public void setInComingSSL(boolean inComingSSL) {
        this.inComingSSL = inComingSSL;
    }

    public String getOutGoingHost() {
        return outGoingHost;
    }

    public void setOutGoingHost(String outGoingHost) {
        this.outGoingHost = outGoingHost;
    }

    public String getOutGoingPort() {
        return outGoingPort;
    }

    public void setOutGoingPort(String outGoingPort) {
        this.outGoingPort = outGoingPort;
    }

    public boolean getOutGoingSSL() {
        return outGoingSSL;
    }

    public void setOutGoingSSL(boolean outGoingSSL) {
        this.outGoingSSL = outGoingSSL;
    }

    public String getProtocol() {
        return protocol;
    }

    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }

    public boolean getDefaultEncryptMail() {
        return defaultEncryptMail;
    }

    public void setDefaultEncryptMail(boolean defaultEncryptMail) {
        this.defaultEncryptMail = defaultEncryptMail;
    }

    public boolean getDefaultSignMail() {
        return defaultSignMail;
    }

    public void setDefaultSignMail(boolean defaultSignMail) {
        this.defaultSignMail = defaultSignMail;
    }
    public boolean getEnabled() {
        return enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    public boolean getOutGoingTLS() {
        return outGoingTLS;
    }

    public void setOutGoingTLS(boolean outGoingTLS) {
        this.outGoingTLS = outGoingTLS;
    }
}
